package plannerGUI;


import PrimoPackage.Planner;
import plannerGUI.FirstPagePlannerGUI;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gabriella
 */
public class CreateAnActivityGUI extends javax.swing.JFrame {
    
    Planner p;

    /**
     * Creates new form CreateAnActivity
     */
    public CreateAnActivityGUI(Planner p) {
        this.p = p;
        initComponents();
        this.setLocationRelativeTo(null);
        for(int i=0; i<p.getActivityList().size(); i++){
        System.out.println(p.getActivityList().get(i).getSite().getId());
        }
    }

    private CreateAnActivityGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    //pulisce i campi 
    public void clearField(){
        jTextFieldId1.setText("");
        jComboBoxTipo1.setSelectedIndex(0);
        jTextFieldDescription1.setText("");
        jTextFieldTime1.setText("");
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);
        jTextFieldWeek1.setText("");
        jTextAreaWorkSpace1.setText("");
    }
    
    // verifica dei dati inseriti
    public boolean verifData(){
        if (jTextFieldId1.getText().equals("")  
                || jTextFieldDescription1.getText().equals("") || jTextFieldTime1.getText().equals("") 
                || jTextFieldWeek1.getText().equals("") 
                ||(jRadioButton3.isSelected() == false) &&(jRadioButton4.isSelected()== false)){
            JOptionPane.showMessageDialog(null, "One or more fields are empty");
            return false;
        }
        if (jTextFieldId1.getText().length()!=6 ){
            JOptionPane.showMessageDialog(null, "ID must has 6 char");
            return false;
        }
        if(Integer.parseInt(jTextFieldTime1.getText())<0 || Integer.parseInt(jTextFieldWeek1.getText())>52){
            JOptionPane.showMessageDialog(null, "Week must be between 1 and 52");
            return false;
        }
        if(p.idControl(jTextFieldId1.getText())== true){
            JOptionPane.showMessageDialog(null, "ID already exists");
            return false;
        }
        else if (jRadioButton3.isSelected() && jRadioButton4.isSelected()){
            JOptionPane.showMessageDialog(null, "You can choose only Yes or No");
            return false;
        }
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBase1 = new CommonComponents.PanelBase();
        closeButton1 = new CommonComponents.CloseButton();
        minimizeButton1 = new CommonComponents.MinimizeButton();
        jLabel1 = new javax.swing.JLabel();
        panelBase2 = new CommonComponents.PanelBase();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldDescription1 = new javax.swing.JTextField();
        jTextFieldId1 = new javax.swing.JTextField();
        jTextFieldTime1 = new javax.swing.JTextField();
        jTextFieldWeek1 = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jComboBoxTipo1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaWorkSpace1 = new javax.swing.JTextArea();
        jComboBox2 = new javax.swing.JComboBox<>();
        operationButton1 = new CommonComponents.OperationButton();
        operationButton2 = new CommonComponents.OperationButton();
        operationButton3 = new CommonComponents.OperationButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel1.setText("Create Activity");

        javax.swing.GroupLayout panelBase1Layout = new javax.swing.GroupLayout(panelBase1);
        panelBase1.setLayout(panelBase1Layout);
        panelBase1Layout.setHorizontalGroup(
            panelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBase1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(minimizeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBase1Layout.setVerticalGroup(
            panelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBase1Layout.createSequentialGroup()
                .addGroup(panelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minimizeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelBase1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        panelBase2.setBackground(new java.awt.Color(245, 171, 53));
        panelBase2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("site:");
        panelBase2.add(jLabel6);
        jLabel6.setBounds(30, 60, 30, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("typology:");
        panelBase2.add(jLabel12);
        jLabel12.setBounds(30, 100, 60, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("activity ID:");
        panelBase2.add(jLabel14);
        jLabel14.setBounds(30, 14, 70, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("activity description:");
        panelBase2.add(jLabel15);
        jLabel15.setBounds(30, 140, 120, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("estimated intervention time:");
        panelBase2.add(jLabel16);
        jLabel16.setBounds(30, 174, 170, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("week:");
        panelBase2.add(jLabel17);
        jLabel17.setBounds(30, 280, 40, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("workspace notes:");
        panelBase2.add(jLabel18);
        jLabel18.setBounds(30, 330, 110, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("interruptible activity:");
        panelBase2.add(jLabel19);
        jLabel19.setBounds(30, 230, 130, 20);

        jTextFieldDescription1.setBackground(new java.awt.Color(253, 227, 167));
        panelBase2.add(jTextFieldDescription1);
        jTextFieldDescription1.setBounds(150, 140, 220, 30);

        jTextFieldId1.setBackground(new java.awt.Color(253, 227, 167));
        jTextFieldId1.setPreferredSize(new java.awt.Dimension(6, 25));
        panelBase2.add(jTextFieldId1);
        jTextFieldId1.setBounds(100, 20, 100, 30);

        jTextFieldTime1.setBackground(new java.awt.Color(253, 227, 167));
        panelBase2.add(jTextFieldTime1);
        jTextFieldTime1.setBounds(200, 180, 110, 30);

        jTextFieldWeek1.setBackground(new java.awt.Color(253, 227, 167));
        panelBase2.add(jTextFieldWeek1);
        jTextFieldWeek1.setBounds(70, 280, 110, 30);

        jRadioButton3.setBackground(new java.awt.Color(253, 227, 167));
        jRadioButton3.setText("YES");
        panelBase2.add(jRadioButton3);
        jRadioButton3.setBounds(160, 230, 50, 23);

        jRadioButton4.setBackground(new java.awt.Color(253, 227, 167));
        jRadioButton4.setText("NO");
        panelBase2.add(jRadioButton4);
        jRadioButton4.setBounds(230, 230, 50, 23);

        jComboBoxTipo1.setBackground(new java.awt.Color(253, 227, 167));
        jComboBoxTipo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electrical", "Electronic", "Hydraulic", "Mechanical" }));
        panelBase2.add(jComboBoxTipo1);
        jComboBoxTipo1.setBounds(90, 100, 100, 20);

        jTextAreaWorkSpace1.setBackground(new java.awt.Color(253, 227, 167));
        jTextAreaWorkSpace1.setColumns(20);
        jTextAreaWorkSpace1.setRows(5);
        jScrollPane2.setViewportView(jTextAreaWorkSpace1);

        panelBase2.add(jScrollPane2);
        jScrollPane2.setBounds(150, 320, 220, 90);

        for(int i=0; i<p.getSiteList().size(); i++){

            jComboBox2.addItem(p.getSiteList().get(i).getId().trim()+':'+ p.getSiteList().get(i).getArea()+'-'+ p.getSiteList().get(i).getFactory());

        };
        panelBase2.add(jComboBox2);
        jComboBox2.setBounds(80, 60, 160, 20);

        operationButton1.setText("Cancel");
        operationButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operationButton1ActionPerformed(evt);
            }
        });
        panelBase2.add(operationButton1);
        operationButton1.setBounds(20, 510, 90, 40);

        operationButton2.setText("View activity");
        operationButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operationButton2ActionPerformed(evt);
            }
        });
        panelBase2.add(operationButton2);
        operationButton2.setBounds(140, 510, 100, 40);

        operationButton3.setText("Create");
        operationButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operationButton3ActionPerformed(evt);
            }
        });
        panelBase2.add(operationButton3);
        operationButton3.setBounds(280, 510, 90, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBase2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBase1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelBase2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void operationButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operationButton1ActionPerformed
        FirstPagePlannerGUI planner= new FirstPagePlannerGUI(p);
        planner.setVisible(true);
        planner.pack();
        planner.setLocationRelativeTo(null);
        planner.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_operationButton1ActionPerformed

    private void operationButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operationButton3ActionPerformed
        if(verifData()){
          p.createActivity(jTextFieldId1.getText(), p.findSiteInList(jComboBox2.getItemAt(jComboBox2.getSelectedIndex()), p.getSiteList()) ,  jComboBoxTipo1.getItemAt(jComboBoxTipo1.getSelectedIndex()), jTextFieldDescription1.getText(), Integer.parseInt(jTextFieldTime1.getText()), jRadioButton3.isSelected(), Integer.parseInt(jTextFieldWeek1.getText()), jTextAreaWorkSpace1.getText());
        JOptionPane.showMessageDialog(rootPane, "create successfully");
        clearField();}
    }//GEN-LAST:event_operationButton3ActionPerformed

    private void operationButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operationButton2ActionPerformed
        ViewActivityGUI view= new ViewActivityGUI(p);
        view.setVisible(true);
        view.pack();
        view.setLocationRelativeTo(null);
        view.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_operationButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAnActivityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAnActivityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAnActivityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAnActivityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAnActivityGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CommonComponents.CloseButton closeButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBoxTipo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaWorkSpace1;
    private javax.swing.JTextField jTextFieldDescription1;
    private javax.swing.JTextField jTextFieldId1;
    private javax.swing.JTextField jTextFieldTime1;
    private javax.swing.JTextField jTextFieldWeek1;
    private CommonComponents.MinimizeButton minimizeButton1;
    private CommonComponents.OperationButton operationButton1;
    private CommonComponents.OperationButton operationButton2;
    private CommonComponents.OperationButton operationButton3;
    private CommonComponents.PanelBase panelBase1;
    private CommonComponents.PanelBase panelBase2;
    // End of variables declaration//GEN-END:variables
}
