package plannerGUI;


import Navigator.Navigator;
import PrimoPackege.Planner;
import javax.swing.JFrame;
import SelectionGUI.SelectActivityGUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gabriella
 */
public class FirstPagePlannerGUI extends javax.swing.JFrame {
    Planner p;

    /**
     * Creates new form FirstPagePlannerGUI
     */
    public FirstPagePlannerGUI(Planner p) {
        initComponents();
        this.p= p;
        //center form
        this.setLocationRelativeTo(null);
    }

    private FirstPagePlannerGUI() {
        initComponents();
        this.p = new Planner();
        this.setLocationRelativeTo(null);
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBase1 = new CommonComponents.PanelBase();
        jLwelcome = new javax.swing.JLabel();
        minimizeButton1 = new CommonComponents.MinimizeButton();
        closeButton1 = new CommonComponents.CloseButton();
        panelBase2 = new CommonComponents.PanelBase();
        jLabel1 = new javax.swing.JLabel();
        operationButton1 = new CommonComponents.OperationButton();
        operationButton2 = new CommonComponents.OperationButton();
        operationButton3 = new CommonComponents.OperationButton();
        operationButton4 = new CommonComponents.OperationButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLwelcome.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLwelcome.setForeground(new java.awt.Color(51, 0, 0));
        jLwelcome.setText("WELCOME PLANNER");

        javax.swing.GroupLayout panelBase1Layout = new javax.swing.GroupLayout(panelBase1);
        panelBase1.setLayout(panelBase1Layout);
        panelBase1Layout.setHorizontalGroup(
            panelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBase1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBase1Layout.createSequentialGroup()
                        .addComponent(jLwelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBase1Layout.createSequentialGroup()
                        .addComponent(minimizeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(closeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panelBase1Layout.setVerticalGroup(
            panelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBase1Layout.createSequentialGroup()
                .addGroup(panelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minimizeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLwelcome)
                .addGap(32, 32, 32))
        );

        panelBase2.setBackground(new java.awt.Color(245, 171, 53));
        panelBase2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Source Code Pro", 0, 18)); // NOI18N
        jLabel1.setText("What are you going to do?");
        panelBase2.add(jLabel1);
        jLabel1.setBounds(170, 100, 290, 23);

        operationButton1.setText("Create activity");
        operationButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operationButton1ActionPerformed(evt);
            }
        });
        panelBase2.add(operationButton1);
        operationButton1.setBounds(40, 210, 120, 50);

        operationButton2.setText("Plan activity");
        operationButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operationButton2ActionPerformed(evt);
            }
        });
        panelBase2.add(operationButton2);
        operationButton2.setBounds(250, 210, 110, 50);

        operationButton3.setText("View activity");
        operationButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operationButton3ActionPerformed(evt);
            }
        });
        panelBase2.add(operationButton3);
        operationButton3.setBounds(460, 210, 100, 50);

        operationButton4.setBackground(new java.awt.Color(255, 0, 0));
        operationButton4.setText("verify Tickets");
        operationButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operationButton4ActionPerformed(evt);
            }
        });
        panelBase2.add(operationButton4);
        operationButton4.setBounds(500, 300, 90, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBase2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(panelBase2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void operationButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operationButton1ActionPerformed
        Navigator nav=Navigator.getInstance(p);
        nav.changeToCreateActivityWindow(this);
        /*CreateAnActivityGUI activity= new CreateAnActivityGUI(p);
        activity.setVisible(true);
        activity.pack();
        activity.setLocationRelativeTo(null);
        activity.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();*/
    }//GEN-LAST:event_operationButton1ActionPerformed

    private void operationButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operationButton2ActionPerformed
        Navigator nav=Navigator.getInstance(p);
        nav.changeToSelectActivityWindow(this);
        /*SelectActivityGUI select= new SelectActivityGUI(p);
        select.setVisible(true);
        select.pack();
        select.setLocationRelativeTo(null);
        select.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();*/
    }//GEN-LAST:event_operationButton2ActionPerformed

    private void operationButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operationButton3ActionPerformed
        Navigator nav=Navigator.getInstance(p);
        nav.changeToViewActivityWindow(this);
        /*ViewActivityGUI view= new ViewActivityGUI(p);
        view.setVisible(true);
        view.pack();
        view.setLocationRelativeTo(null);
        view.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();*/
    }//GEN-LAST:event_operationButton3ActionPerformed

    private void operationButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operationButton4ActionPerformed
       Navigator nav=Navigator.getInstance(p);
       nav.changeToTicketList(this);
        /* TicketList view= new TicketList(p);
        view.setVisible(true);
        view.pack();
        view.setLocationRelativeTo(null);
        view.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();*/
    }//GEN-LAST:event_operationButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstPagePlannerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstPagePlannerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstPagePlannerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstPagePlannerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstPagePlannerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CommonComponents.CloseButton closeButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLwelcome;
    private CommonComponents.MinimizeButton minimizeButton1;
    private CommonComponents.OperationButton operationButton1;
    private CommonComponents.OperationButton operationButton2;
    private CommonComponents.OperationButton operationButton3;
    private CommonComponents.OperationButton operationButton4;
    private CommonComponents.PanelBase panelBase1;
    private CommonComponents.PanelBase panelBase2;
    // End of variables declaration//GEN-END:variables
}
